from __future__ import annotations

from datetime import timedelta

DOMAIN = "startedu"

CONF_BASE_URL = "base_url"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_BREAKFAST_TIME = "breakfast_time"
CONF_LUNCH_TIME = "lunch_time"
CONF_AFTERNOON_SNACK_TIME = "afternoon_snack_time"
CONF_OTHER_MEAL_TIME = "other_meal_time"

DEFAULT_BASE_URL = "https://startedu.pl/"
DEFAULT_SCAN_INTERVAL_MINUTES = 1440
MIN_SCAN_INTERVAL_MINUTES = 60
MAX_SCAN_INTERVAL_MINUTES = 1440
DEFAULT_BREAKFAST_TIME = "08:00"
DEFAULT_LUNCH_TIME = "12:00"
DEFAULT_AFTERNOON_SNACK_TIME = "14:30"
DEFAULT_OTHER_MEAL_TIME = "12:00"
DEFAULT_BREAKFAST_DURATION_MINUTES = 30
DEFAULT_LUNCH_DURATION_MINUTES = 45
DEFAULT_AFTERNOON_SNACK_DURATION_MINUTES = 30
DEFAULT_OTHER_MEAL_DURATION_MINUTES = 30

PLATFORMS = ["calendar", "sensor", "binary_sensor", "button"]
DEFAULT_UPDATE_INTERVAL = timedelta(minutes=DEFAULT_SCAN_INTERVAL_MINUTES)
